In [ ]:
#1. Shape

#2. nDim

#3. Size

#4. Itemsize

#5. Dtype

#6. astype()


In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1.shape

(5,)

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2
arr2.shape

(2, 3)

In [10]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3
arr3.shape#2 row 2 column aur aise 2 matrix hai isiliye(2,2,2) print hoga

(2, 2, 2)

In [11]:
arr1.ndim#yaha basically dimension hi bataya jaayega

1

In [12]:
arr2.ndim

2

In [13]:
arr3.ndim

3

In [14]:
arr1.size

5

In [16]:
arr4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr4.size #integer hai isiliye item size 4 rahega, float mey 8 aayega

8

In [18]:
arr1.itemsize

4

In [19]:
arr4.itemsize

4

In [20]:
arr2.itemsize

4

In [21]:
arr3.itemsize

4

In [24]:
arr5 = np.linspace(10,20,10)
arr5

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [23]:
arr5.itemsize #float hai isiliye itemsize 8 aaya hai.

8

In [25]:
arr5.dtype #float aayega

dtype('float64')

In [26]:
arr4.dtype

dtype('int32')

In [27]:
arr4.astype('float') #integer ko float mey convert karke likh diya hai.

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [29]:
arr5.astype('int') #yaha humne float ko int mey convert kar diya hai.
#astype function ka kaam data cleaning mey padhta hai.

#bade data set mey float values wagera jyada space khati hai is wajah se 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])