In [1]:
import numpy as np

In [2]:
#Scenario 1

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
#a1 aur a2 ka har element ka individually addition hua hai
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
#Scenario 2

a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [8]:
#a3 mey 3 row and 3 column hai
#and a4 mey 1 row aur 3 column hai

#ab yaha numpy kya klarega ki a3 aur a4 ko add kar dega 
#karega aise ki bhai a 3 ke har row mey row wise a4 ko add kar dega

a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
# The term broadcasting refers to the ability of NumPy to treat arrays of different 
# shapes during arithmetic operations.

# Arithmetic operations on arrays are usually done on corresponding elements. 
# If two arrays are of exactly the same shape, then these operations are smoothly performed.

# If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. 
# However, operations on arrays of non-similar shapes is still possible in NumPy, because of 
# the broadcasting capability. 

# The smaller array is broadcast to the size of the larger array so that thay have compatible shapes.

Rules For Broadcasting

In [10]:
#If x=m and y=n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [11]:
#If x=1 and y=n then also operation will take place(Same Dimension)

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)

print(a5,a6)

[[0 1 2]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
a5 + a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [13]:
#If y=1 and x=m then also operation will take place, even if
#they are not of the same dimension

a7=np.arange(4).reshape(1,4)
a8=np.arange(12).reshape(3,4)

print(a7)
print(a8)


[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a7 + a8

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [15]:
# If x=1 and y!=n then also operation will not take place

a9=np.arange(3).reshape(1,3)
a10=np.arange(16).reshape(4,4)

print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
#a9 + a10 yaha error aayega kyuki dimension gadbad hai

In [18]:
#If x=1 and n=1 then y==m, operation to take place

a11=np.arange(3).reshape(1,3)
a12=np.arange(3).reshape(3,1)

print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [19]:
a11 + a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [20]:
#If x=1 and y=1, then the operation will take place no matter what

a13=np.arange(1).reshape(1,1)
a14=np.arange(20).reshape(4,5)

print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
a15=np.arange(4)
a16=np.arange(20).reshape(5,4)

print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [23]:
a15 + a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])