In [ ]:
#1. using np.array()//1-D and 2-D

#2. Using np.zeroes/ones/empty/random()

#3. Using np.arange()

#4. Using np.linspace()

#5. Using Copy()

#6. Using Identity()


In [1]:
#creating numpy/n-d arrays
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [2]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#yaha humne kiya kya hai ki ek tuple banaya hai jisme humne dimensions bata diye hai(2rows and 3 columns)
#to us dimension ki matrix ban gyi hai and kyuki humne shurwaat mey zeros bola tha to har position pr zero print hoga.
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#2,3 dimension ki matrix bana di jaha pr har element ki value 1 hogi
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#yaha kya hua ki humne bola 5x5 ki matrix banao and usme diagonal elements 1 print hoge and baaki saare position ke elements zero print hoge
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#yaha kya hoga ki ek list generate hogi and elements 0 se le kar 9 tak present hoge.
arr6=np.arange(10)
arr6
#agar 5 se le kar 15 tk element print karna ho to
arr7=np.arange(5,16)
arr7
#agar 5 se 15 tk element print karna hai ek-ek place chor kr 
arr8=np.arange(5,16,2)#indexing and slicing ka concept
arr8

array([ 5,  7,  9, 11, 13, 15])

In [13]:
#10 se le kar 20 ke bich mey 10 equidistant points
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
#pichle array ki copy print karrana ho to
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])