In [1]:
import numpy as np

In [12]:
#ek array  hai jiski size hai 24
arr1 = np.arange(24).reshape(6,4)#yaha kya kiya hai ke simply bol diya ki normal array ko aise shape karo such tha
#it has 6 rows and 4 columns
arr1
# arr2 = arr1.reshape(6,4)
# print(arr2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
arr2 = np.array([1,2,3,4,5,6,7])
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
arr2[3]#index 3 ki value 
arr2[-2]#piche se dusre index ki value

6

In [16]:
arr1[2]#3rd row ko print karega

array([ 8,  9, 10, 11])

In [18]:
arr1[:2]#pehle ke 2 row print hoge

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
arr1[2:]#pehle ke 2 row chor kar saare print hoge

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#agar column print karana hai to 
arr1[:,3] #last column print karne ke liye

array([ 3,  7, 11, 15, 19, 23])

In [22]:
arr1[:,1:3]#index 1 aur 2 waale column print hoge

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [25]:
#9,10
#13,14 print karana tha , to kya krege ki
arr1[2:4,1:3]#row mey index 2 se le kar 4 ke bich rows utha lo and index 1se le kar 3 ke bich ke column utha lo
#to desired output aa jaayega.

array([[ 9, 10],
       [13, 14]])

In [26]:
#similarly maan lo print karna ho
#18,19
#22,23

arr1[4:,2:] #index 4th row se le kar aakhri row tk select kiya and index 2nd column se le kar aakhri column tk humare kaam ka tha
#is se desired output aa jaayega

array([[18, 19],
       [22, 23]])

In [27]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [28]:
#agar maan lo saaare elements ek hi column mey print karane ho to nditer use karte hai
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
