In [4]:
import numpy as np

In [5]:
arr1=np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr1

array([[44, 51, 49, 54, 72],
       [56, 93, 47, 89, 73],
       [59, 34, 13, 96, 12],
       [48, 62, 93, 75, 64]])

In [6]:
arr1[0]#pehli row milegi
arr1[0,2]#0 row second column ka element fetch hoga

49

In [7]:
arr1>50# jo value 50 se badi hai waha True print hoga else False print hogs

array([[False,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True, False, False,  True, False],
       [False,  True,  True,  True,  True]])

In [8]:
#arr1 mey jo bhi elements 50 se bade they uski new array bana do 
arr1[arr1>50]

array([51, 54, 72, 56, 93, 89, 73, 59, 96, 62, 93, 75, 64])

In [9]:
#ek new array bana rhe hai jisme niche ki 2 condition satisfy karne waale numbers hai.
arr1[(arr1>50) & (arr1%2!=0)]

array([51, 93, 89, 73, 59, 93, 75])

In [10]:
arr1[(arr1>50) & (arr1%2!=0)]=0
arr1

array([[44,  0, 49, 54, 72],
       [56,  0, 47,  0,  0],
       [ 0, 34, 13, 96, 12],
       [48, 62,  0,  0, 64]])