In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [5]:
#pehli array mey se dusri array ko subrtract kar rahe hai element wise
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [7]:
#element wise multiplication
arr1*arr2 #vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [8]:
#pehli array ko 2 se multiply karne ke baad element wise multipliesd array output mey aayegi
arr1*2#scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [9]:
#Yaha hum puch rhe hai ki arr1 ka kon kon sa element 3 se bada hai.
#jaha bada hai waha True print hoga jaha chota hai waha False print hoga.
arr1>3

array([False, False, False,  True,  True,  True])

In [10]:
#2 matrix bana di hai and and uska dot product kiya hai.
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [11]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
#4th array ki minimum value nikaalne ke liye
arr4.min()

6

In [13]:
#Agaar nikaalna ho ki konse row ke element sab se chote hai
#axis = 0 matlab row
arr4.min(axis=0)

array([6, 7])

In [14]:
#Agaar nikaalna ho ki konse column ke element sab se chote hai
#axis = 1 matlab column
arr4.min(axis=1)

array([ 6,  8, 10])

In [15]:
arr4.sum()

51

In [16]:
arr4.sum(axis=0)

array([24, 27])

In [17]:
arr4.sum(axis=1)

array([13, 17, 21])

In [18]:
arr4.mean()

8.5

In [19]:
arr4.std()#standard deviation

1.707825127659933

In [21]:
np.median(arr4)

8.5

In [20]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [22]:
#ab ek khel hai yaha par
#functions ko 2 tarike se call kiya jaa rha hai.

#basically classes and objects ka khel hai(OOPs)

#pehla arr4.mean() mtlb hum function ko object bana kar call kar rhe hai
# np.median(arr4) mtlb hum jab function ko call kar rahe hai to object banane ki zarurat nahi hai.
#directly function call hoga.

In [23]:
np.exp(arr4)#exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])