In [33]:
import numpy as np

In [34]:
#ravel function kya krta hai ki higher dimension array ko one dimension array mey le kar aata hai
arr1 = np.arange(6,12).reshape(3,2)
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
arr1.ndim #matlab humari array 2 dimesion ki hai.

2

In [36]:
arr1.ravel()#ravel function 1 dimension mey covert karega

array([ 6,  7,  8,  9, 10, 11])

In [37]:
x = arr1.ravel()#test karne ke liye arr4.ravel() ko x mey store kiya and x ki dimension nikal li
x.ndim

1

In [38]:
arr1.transpose()#row ka column aur column ka row ho jaayega transpose mey

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [39]:
arr2 = np.arange(6).reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
arr3=np.arange(12,18).reshape(2,3)
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [41]:
np.hstack((arr2,arr3))#horizontal stacking
#2 bracket isiliye kyuki hum 2 attribute andar pass kar rhe hai

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [42]:
np.vstack((arr2,arr3))#vertical stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [43]:
# Ab vertical stacking ka use kya hai?

# Maan lo ki aap ek clg ke liye student biodata sheet bana rhe ho
# Waha variables such as name, age, roll number to har insaan ke liye same rahege 
# magar unki values alag rahegi

# But kyuki values same hai to usey hum ekl saath stack kreke
# store kar sakte hai, 
# jaise generally CSV files mey hota hai.

In [45]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.hsplit(arr2, 3) #arr2 ke baad 3 isiliye kyuki 1 row mey 3 element hai.

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [47]:
np.vsplit(arr2, 2) # arr2 ke baad 2 isiliye kyuki har column mey 2 element hai

[array([[0, 1, 2]]), array([[3, 4, 5]])]