In [1]:
import numpy as np

In [4]:
#koi bhi random value print hogi
np.random.random()

0.6138561565667092

In [10]:
#ab maan lo ki aapko random value to chahiye magar 
#baar baar run karne ke baad bhi same hi value print karana chahte ho
#to use krte hai seed function----seed ke andar koi bhi value daal do
np.random.seed(15)
np.random.random()

0.8488176972685787

In [15]:
#ab maan lo aap chah rhe ho ki ek random value chahiye 
#lekin vo koi 2 number ke bich ki koi bhi value hai
#quite simply ek range ki random value ho 
np.random.uniform(4,7)

5.5900006746862765

In [16]:
# ab maan lo kisi range mey kuch amount of random numbers chahiye
np.random.uniform(2,50,20)#2 se le kar 50 range hai and 20 values print hogi

array([16.68410796, 16.61476924,  7.36358126, 13.99515267, 46.0462351 ,
       14.67904896, 36.453137  , 43.55432164, 40.73981515, 12.10642797,
       10.02766551,  4.2419068 ,  3.89227096, 11.61107887, 49.93008333,
       19.89377496, 38.50449315, 24.72677325, 26.46633468, 47.36184403])

In [18]:
#ab above generated array ko matrix mey convert karna hai to
np.random.uniform(2,50,20).reshape(4,5)

array([[ 8.36644725,  3.47627041, 32.69549256, 23.40791108, 48.78111851],
       [17.82876475, 11.38039151, 34.83421819, 18.85274515, 39.00973344],
       [40.00637607, 23.30598028, 14.90375846,  3.14741226, 19.82396316],
       [ 6.69108222, 36.92108233, 24.05333242, 26.98383079, 34.85931406]])

In [19]:
#koi range ke bich mey random integer value chahiye to
np.random.randint(1,10)

4

In [20]:
#kisi range mey multiple integer values chahiye to
np.random.randint(2,50,10)

array([ 5, 39, 46, 21, 17, 18, 45, 34, 35, 36])

In [21]:
#ab upar waali array ko matrix banana hai to
np.random.randint(2,50,10).reshape(2,5)

array([[35, 30, 38, 25, 10],
       [41, 12, 44, 13, 45]])

In [24]:
a=np.random.randint(1,10,6)
a

array([5, 2, 1, 5, 8, 9])

In [25]:
#random number s e bani hu array mey agar maximum element nikaalna ho to
np.max(a)

9

In [26]:
#minimum value nikaalni ho to
np.min(a)

1

In [30]:
#agar maximum value ka index chahiye to argmax use karte hai
np.argmax(a)

5

In [31]:
#maximum value nikaalne ka ek aur tarika
a[np.argmax(a)]

9

In [32]:
#minimum value nikaalne ka ek aur tarika
a[np.argmin(a)]

1

In [33]:
#minimum value ka index
np.argmin(a)

2

In [35]:
#maan lo given array mey se odd numbers ko hatana hai aur kisi aur number se replace karna hai
a[a%2==1]=-1
a

array([-1, -1, -1, -1, -1, -1])

In [36]:
a=np.random.randint(1,20,7)
a

array([ 6,  4, 17, 17, 12,  2, 10])

In [37]:
#odd number ke jagah par -1 print ho gya
np.where(a%2==1,-1,a)

array([ 6,  4, -1, -1, 12,  2, 10])

In [39]:
#ab new array ko kisi aur variabkle mey store kar lete hai.
b = np.where(a%2==1,-1,a)
b

array([ 6,  4, -1, -1, 12,  2, 10])

In [40]:
c=np.random.randint(2,200,40)
c

array([ 76,  70,  39,  29,  29,  74, 149, 109,  59, 161,  19, 125, 119,
        19,  72,  50,  27, 161, 110, 169,  90,  37, 172,  70, 155,  59,
       140, 177,  36, 115,  45,  36, 198,  68, 106,  19,  25,  62, 183,
        42])

In [43]:
#upar waali array ko ascending mey order mey sort karna ho to
c=np.sort(c)
c

array([ 19,  19,  19,  25,  27,  29,  29,  36,  36,  37,  39,  42,  45,
        50,  59,  59,  62,  68,  70,  70,  72,  74,  76,  90, 106, 109,
       110, 115, 119, 125, 140, 149, 155, 161, 161, 169, 172, 177, 183,
       198])

In [45]:
#maanlo pata lagana ho ki jo aapki array hai
#kisi particular percent pr konse number se niche numbers rahege

#jaise yaha pr ye dekhoge ki 40 percent number 60 se niche ke hai

#marks ki array mil gyi ye nikaalna ho ki bhai 99 percentile mtlb kitne number hue to dikh jaayega
np.percentile(c,40)
np.percentile(c,99)

192.14999999999998